Proj 15 frontend as a user i want to crud my account
frokostklubben/frontend pull request #9
Opened 2023-03-22 13:47 UTC by norskemarcus

I have deleted a lot of unused files

2023-03-22 13:50 UTC, tomm8231 commented on index.js
> +  //const templateLogin = await loadHtml("./pages/login/login.html");
indkommentér

2023-03-22 17:28 UTC, norskemarcus commented on index.js
> +  //const templateLogin = await loadHtml("./pages/login/login.html");
Remove this comment

2023-03-22 18:49 UTC, tomm8231 requested changes
U do u

2023-03-23 07:45 UTC, tomm8231 approved these changes

2023-03-23 07:46 UTC, merged